CREATE TABLE task (
    id INTEGER NOT NULL PRIMARY KEY,
    list_id INTEGER NOT NULL DEFAULT 1 REFERENCES list(id) ON UPDATE CASCADE,
    done BOOLEAN NOT NULL DEFAULT FALSE,
    contents VARCHAR NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due TIMESTAMP,
    remind_at TIMESTAMP,
    starred BOOLEAN NOT NULL DEFAULT FALSE,
    note TEXT
)