CREATE TABLE task (
    id INTEGER NOT NULL PRIMARY KEY,
    list_id INTEGER REFERENCES list(id) ON UPDATE CASCADE,
    done BOOLEAN NOT NULL DEFAULT FALSE,
    contents VARCHAR NOT NULL,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due DATETIME,
    remind_at DATETIME,
    starred BOOLEAN NOT NULL DEFAULT FALSE,
    note TEXT
)